export const SINGLEPLAYER_UPDATED = "SINGLEPLAYER_UPDATED";
export const MULTIPLAYER_UPDATED = "MULTIPLAYER_UPDATED";

export const EXPERIENCE_UPDATED = "EXPERIENCE_UPDATED";
export const SETTINGS_UPDATED = "SETTINGS_UPDATED";

export const ACHIEVEMENT_AWARDED = "ACHIEVEMENT_AWARDED";

export const USER_CONNECTED = "USER_CONNECTED";
export const USER_DISCONNECTED = "USER_DISCONNECTED";