export const SINGLEPLAYER_UPDATED = "SINGLEPLAYER_UPDATED";
export const EXPERIENCE_UPDATED = "EXPERIENCE_UPDATED";
export const SETTINGS_UPDATED = "SETTINGS_UPDATED";

export const ACHIEVEMENT_AWARDED = "ACHIEVEMENT_AWARDED";
