name: "E2E"
on:
  push:
    branches:
      - next

jobs:
  cypress-run:
    name: E2E
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - uses: cypress-io/github-action@v5
        with:
          start: npm run dev
          wait-on: 'http://localhost:3000'
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
